version: '3'
services:
  nginx:
    # image: nginx:stable
    build: .
    depends_on:
      - ghost
    links:
      - ghost
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./gopl-zh:/opt/gopl-zh
    restart: always
    container_name: nginx
    ports:
     - 80:80
  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    volumes:
      - /data1/ghost/mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: change_password
  ghost:
    image: ghost:3
    restart: always
    container_name: ghost
    #ports:
    #  - 3001:2368
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: root
      database__connection__password: change_password
      database__connection__database: ghost
      url: https://www.itsfun.top
    volumes:
      - /data1/ghost/ghost-data:/var/lib/ghost/content

